dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,11)
Orden:2591199602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz















ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
30-11-2020 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,11)
Orden:2591473602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz















ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
19-02-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,14)
Orden:2622462
1419: Para facturas B (CbteDesde igual a CbteHasta) menor a $20932, si DocTipo es distinto a 99, DocNro debe ser mayor a 0.
602: No existen datos en nuestros registros para los parametros ingresados.
22-04-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,11)
Orden:2643747602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz















ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
22-04-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,11)
Orden:2643747602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz















ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
22-04-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(7,11)
Orden:2644477
1491: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.
602: No existen datos en nuestros registros para los parametros ingresados.
22-04-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,11)
Codigo error afip:*****
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 345, in CompUltimoAutorizado
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "p















ysimplesoap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)

Linea de codigo de error: UltCBTE = WSFE.CompUltimoAutorizado(cTipoCbte, cPrefijo)
Procedimiento: sw_ultimocomproba
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 345, in CompUltimoAutorizado
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimple















soap\client.pyc", line 354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)
.

Exepción: AttributeError: Tag not found: Body (No elements found)

Traceback: Traceback (most recent call last):
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 345, in CompUltimoAutorizado
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimplesoap\client.pyc", line 















354, in wsdl_call
  File "pysimplesoap\simplexml.pyc", line 362, in __call__
AttributeError: Tag not found: Body (No elements found)


22-04-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(7,11)
Orden:2644477
805: De enviarse el tag CbtesAsoc, CbteAsoc debe enviarse con Tipo mayor a 0
602: No existen datos en nuestros registros para los parametros ingresados.
22-04-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(7,11)
Orden:2644477
805: De enviarse el tag CbtesAsoc, CbteAsoc debe enviarse con Tipo mayor a 0
602: No existen datos en nuestros registros para los parametros ingresados.
01-12-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,11)
Orden:2723347602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz















ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
01-12-2021 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,11)
Orden:2723347602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz















ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
10-01-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,17)
WSFE.CompUltimoAutorizado(2,17)
WSFE.CompUltimoAutorizado(3,17)
WSFE.CompUltimoAutorizado(6,17)
WSFE.CompUltimoAutorizado(7,17)
WSFE.CompUltimoAutorizado(8,17)
WSFE.CompUltimoAutorizado(6,17)
Orden:68602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
10-01-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,17)
WSFE.CompUltimoAutorizado(2,17)
WSFE.CompUltimoAutorizado(3,17)
WSFE.CompUltimoAutorizado(6,17)
WSFE.CompUltimoAutorizado(7,17)
WSFE.CompUltimoAutorizado(8,17)
WSFE.CompUltimoAutorizado(8,17)
Orden:422
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
602: No existen datos en nuestros registros para los parametros ingresados.
07-03-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Orden:2761965
1491: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.
602: No existen datos en nuestros registros para los parametros ingresados.
07-03-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Orden:2761965
1491: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.
602: No existen datos en nuestros registros para los parametros ingresados.
21-03-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(3,11)
Orden:2771631
1491: Si el comprobante es Debito o Credito, enviar estructura CbteAsoc o PeriodoAsoc.
602: No existen datos en nuestros registros para los parametros ingresados.
01-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Orden:2789155
802: De enviarse el tag CbtesAsoc debe enviarse PtoVta mayor a 0
602: No existen datos en nuestros registros para los parametros ingresados.
02-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
02-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
02-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1585). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,14)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28















2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys















implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1249). ---> Input string was not in a correct format.

















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _















invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso















ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1249). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1249). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,14)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28














2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys














implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1249). ---> Input string was not in a correct format.
















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _














invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso














ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1249). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1249). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,14)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28













2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys













implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1253). ---> Input string was not in a correct format.















Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _













invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso













ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1253). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1253). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(2,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28












2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys












implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1583). ---> Input string was not in a correct format.














Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _












invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso












ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1583). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1583). ---> Input string was not in a correct format.
03-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(2,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28











2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys











implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1583). ---> Input string was not in a correct format.













Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _











invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso











ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1583). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1583). ---> Input string was not in a correct format.
06-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(3,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28










2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys










implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1592). ---> Input string was not in a correct format.












Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _










invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso










ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1592). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1592). ---> Input string was not in a correct format.
22-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(3,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28









2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys









implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.











Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _









invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso









ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
22-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(3,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28








2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys








implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.










Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _








invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso








ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
22-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(3,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28







2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys







implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.









Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _







invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso







ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
22-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(3,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28






2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys






implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.








Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _






invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso






ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1591). ---> Input string was not in a correct format.
22-06-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(3,11)
Codigo error afip:0
Numero de Error: 1429
Mensaje de Error: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 28





2, in _invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pys





implesoap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1588). ---> Input string was not in a correct format.







Linea de codigo de error: cCAEA = WSFE.CAEARegInformativo()
Procedimiento: inf_proceso
Error VFP: Código de excepción OLE IDispatch 0 de Python COM Server Internal Error: Unexpected Python Error: Traceback (most recent call last):
  File "win32com\server\policy.pyc", line 277, in _Invoke_
  File "win32com\server\policy.pyc", line 282, in _





invoke_
  File "win32com\server\policy.pyc", line 585, in _invokeex_
  File "utils.pyc", line 157, in capturar_errores_wrapper
  File "wsfev1.pyc", line 798, in CAEARegInformativo
  File "pysimplesoap\client.pyc", line 148, in <lambda>
  File "pysimpleso





ap\client.pyc", line 352, in wsdl_call
  File "pysimplesoap\client.pyc", line 223, in call
SoapFault: soap:Client: Server was unable to read request. ---> There is an error in XML document (5, 1588). ---> Input string was not in a correct format.
.

Exepción: 
Traceback: 

Server was unable to read request. ---> There is an error in XML document (5, 1588). ---> Input string was not in a correct format.
28-09-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,14)
Orden:2840801602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz




ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
28-09-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(6,14)
Orden:2840801602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutoriz



ado.

602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
04-11-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,14)
Orden:2845743
805: De enviarse el tag CbtesAsoc, CbteAsoc debe enviarse con Tipo mayor a 0
602: No existen datos en nuestros registros para los parametros ingresados.
04-11-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,14)
Orden:2845743
805: De enviarse el tag CbtesAsoc, CbteAsoc debe enviarse con Tipo mayor a 0
602: No existen datos en nuestros registros para los parametros ingresados.
04-11-2022 , 
1.23b 
C:\APLICA~1\PyAfipWs
appserver status OK
dbserver status OK
authserver status OK
WSFE.CompUltimoAutorizado(1,11)
WSFE.CompUltimoAutorizado(2,11)
WSFE.CompUltimoAutorizado(3,11)
WSFE.CompUltimoAutorizado(6,11)
WSFE.CompUltimoAutorizado(7,11)
WSFE.CompUltimoAutorizado(8,11)
WSFE.CompUltimoAutorizado(8,14)
Orden:2845743
805: De enviarse el tag CbtesAsoc, CbteAsoc debe enviarse con Tipo mayor a 0
602: No existen datos en nuestros registros para los parametros ingresados.
28-12-2022 , 1.23b C:\APLICA~1\PyAfipWsappserver status OKdbserver status OKauthserver status OKWSFE.CompUltimoAutorizado(1,11)WSFE.CompUltimoAutorizado(2,11)WSFE.CompUltimoAutorizado(3,11)WSFE.CompUltimoAutorizado(6,11)WSFE.CompUltimoAutorizado(7,11)WSFE.CompUltimoAutorizado(8,11)WSFE.CompUltimoAutorizado(6,11)Orden:2865386602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.602: No existen datos en nuestros registros para los parametros ingresados.
703: El numero de comprobante informado debe ser mayor en 1 al ultimo informado para igual punto de venta y tipo de comprobante. Consultar metodo FECompUltimoAutorizado.
